name: VanillaPlusTweaks
version: '${project.version}'
main: me.unleqitq.vanillaplustweaks.VanillaPlusTweaks
api-version: 1.17
load: STARTUP
authors: [ UnleqitQ ]
commands:
  vanillaplustweaks:
    description: Reload Vanilla Plus Tweaks
    permission: vpt.admin.reload
permissions:
  vpt.admin.reload:
    description: Reload the plugin
    default: op
